updates
has-lab/has-lab.github.io pull request #19
Opened 2020-12-04 13:42 UTC by huangweizhou

2020-12-05 05:43 UTC, janzhou requested changes

2020-12-05 05:43 UTC, janzhou commented on _posts/2020-12-4-tailored-page-sizes.md
> +<img src="../images/pagewalk_overhead.png" width="75%" height="65%" />
图片链接去掉2点，用：/images/pagewalk_overhead.png

另外，图片地址统一加上日期，将来方便找到是哪篇文章用的。

还有你的修改为什么带了这么多图片？文章只用了3张？

2020-12-05 05:43 UTC, janzhou commented on _posts/2020-12-4-tailored-page-sizes.md
> +[文章来源](https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=9138990)
用这个链接：

```
[Tailored Page Sizes](https://conferences.computer.org/isca/pdfs/ISCA2020-4QlDegUf3fKiwUXfV0KdCm/466100a900/466100a900.pdf)
```

2020-12-05 05:43 UTC, janzhou commented on _posts/2020-12-4-tailored-page-sizes.md
> +tags:
tags标记一下会议和年份

2020-12-05 05:43 UTC, janzhou commented on _posts/2020-12-4-tailored-page-sizes.md
> +本文通过修改PTE格式和TLB硬件缓存实现了任意大小($\geq$ 4KB)的内存页映射
这句可以放到开头

2020-12-05 05:43 UTC, janzhou commented on _posts/2020-12-4-tailored-page-sizes.md
> +# Tailored Page Sizes
删掉

2020-12-05 05:43 UTC, janzhou commented on _posts/2020-12-4-tailored-page-sizes.md
> +[ZSim](https://people.csail.mit.edu/sanchez/papers/2013.zsim.isca.pdf)，一种基于循环的x86超量的无序处理器模拟器
这篇文章没有做全系统仿真，因为作者说会花几个月时间。TLB部分是模拟的。仿真了内存分配、TLB缓存、MMU缓存等。

你认为让这篇文章被ISCA接收，最重要的原因是什么？

2020-12-05 05:43 UTC, janzhou commented on _posts/2020-12-4-tailored-page-sizes.md
> +如图2所示，当内存页映射大小每翻一倍，其对应的PFN号所需要的比特数减少一位，因此可以通过检查PTE的第20-12位中有多少位用于表示PFN就可以判断这个PTE表示的页映射尺寸（仅限于4B-2MB范围的映射大小)。相当于复用了PTE的20-12位记录页映射的尺寸。
是不是先介绍一下以前的页表格式？或者给出相应链接。

https://www.kernel.org/doc/gorman/html/understand/understand006.html

为什么可以复用20-12位？

2020-12-05 05:43 UTC, janzhou commented on _posts/2020-12-4-tailored-page-sizes.md
> +随着系统物理内存容量的增加，映射条目（PTE）急剧增加，而TLB缓存大小由于成本等问题而受到限制，导致TLB缓存命中率降低，地址转换过程需要频繁的访问内存，带来高额的延时，一些应用甚至有50%的执行时间都花在查询内存页表上。图1描述了在不同负载下应用访问内存页表占应用总执行时间的比例。
哪些应用有50%的执行时间花在查询内存页表上？图1是大页映射还是4KB？Native、SMT、Virtualized代表什么？

2020-12-07 03:54 UTC, huangweizhou commented on _posts/2020-12-4-tailored-page-sizes.md
> +[ZSim](https://people.csail.mit.edu/sanchez/papers/2013.zsim.isca.pdf)，一种基于循环的x86超量的无序处理器模拟器
他的研究方向很有意思，利用了新型的TLB（连续性感知的TLB），将大页映射交给TLB，而软件只用负责映射的连续性就行
他的设计很巧（只用了1位元数据，即PTE保留位）

2020-12-07 04:01 UTC, huangweizhou commented on _posts/2020-12-4-tailored-page-sizes.md
> +[ZSim](https://people.csail.mit.edu/sanchez/papers/2013.zsim.isca.pdf)，一种基于循环的x86超量的无序处理器模拟器
应该是问题比较新，在这篇论文之前没有研究实现**任意**尺寸的页映射。
然后作者通过一个例子将变长尺寸的页映射和解决映射开销问题很好地扣在了一起。
然后设计上很巧妙，不会一下子让人想到，但是却做得很简洁，容易让人接受。

2020-12-07 05:50 UTC, huangweizhou commented on _posts/2020-12-4-tailored-page-sizes.md
> +随着系统物理内存容量的增加，映射条目（PTE）急剧增加，而TLB缓存大小由于成本等问题而受到限制，导致TLB缓存命中率降低，地址转换过程需要频繁的访问内存，带来高额的延时，一些应用甚至有50%的执行时间都花在查询内存页表上。图1描述了在不同负载下应用访问内存页表占应用总执行时间的比例。
![image](https://user-images.githubusercontent.com/64565864/101314278-24949f80-3893-11eb-9a97-be6df6f65daa.png)
要不我不说50%，简单描述下图片中的数据

2020-12-07 05:52 UTC, merged